### ISSUE TITLE
can i have the code used in Drop-seq?

### ISSUE THREAD

**Issue by x1han** [zhoujoeyyi/humanImmatureNeurons#1]
hi zhou,
  thanks a lot for the excellent bioinformatic works in **_Molecular landscapes of human hippocampal immature neurons across lifespan_**, but when i checked the Code availability for some information about the alignment of the data you used, eagerly to rerun it in some day, i got only the machine learning code in python. I'm wandering can you please post the Drop-seq pipeline code on this repository or send by email to hxsci@outlook.com.

  many thanks, hoping for reply.

**Comment by zhoujoeyyi** [comment]
The issue was addressed through email communication on 9/17/2022.
