### ISSUE TITLE
Annotaion files or process codes of AD dataset

### ISSUE THREAD

**Issue by WJPina** [zhoujoeyyi/humanImmatureNeurons#3]
Hi, zhou, your results in AD dataset are inspiring but it's hardly to reproduce due to neither the annotaion file nor process codes are avaliable, I'll be gratedful if you like to mail me this files.
ps: 21212030014@m.fudan.edu.cn

**Comment by zhoujoeyyi** [comment]
The issue was addressed through email communication on 12/12/2022.
