### ISSUE TITLE
infant_hip.pkl request

### ISSUE THREAD

**Issue by marvinquiet** [zhoujoeyyi/humanImmatureNeurons#4]
Dear Dr. Zhou,

Thank you for your nice work in publishing "Molecular landscapes of human hippocampal immature neurons across lifespan" and I would like to follow your ML approach in our study.

I wonder if it is convenient for you to send me this pkl data `infant_hip.pkl` to my email: wenjing.ma@emory.edu so that I can easily follow the pipeline. Thank you in advance and congratulations to you on publishing your work!

Sincerely,
Wenjing

**Comment by zhoujoeyyi** [comment]
The issue was addressed through email communication on 4/21/2023.
