### ISSUE TITLE
data and annotation

### ISSUE THREAD

**Issue by ChuanXu1** [zhoujoeyyi/humanImmatureNeurons#5]
Hi!

Thank you for this great resource! Could I have your processed count data with corresponding cell type annotation, such as the dataset in Fig. 2a? Thank you.

**Comment by zhoujoeyyi** [comment]
Hi @ChuanXu1 , 
Sure, happy to. Please email me at yzhou1@upenn.edu so that I can share the cell annotation files with your email through Google Drive.

Best,
Joey
