### ISSUE TITLE
infant_hip data request 

### ISSUE THREAD

**Issue by ZhongzeYan** [zhoujoeyyi/humanImmatureNeurons#6]
Hi, Dr. Zhou, Your work is very great and meaningful ! I am working on my research following your ML pipeline. And there are some difficulties in my work these days. Would you please send the infant_hip.pkl to my email? That's will be very important for me to solve my problem. I will be very grateful for that. Email: yanzhongze@ioz.ac.cn.  
Thank you again!
Yan

**Comment by zhoujoeyyi** [comment]
Request fulfilled.
