### ISSUE TITLE
Cell's metadata

### ISSUE THREAD

**Issue by ariberar** [zhoujoeyyi/humanImmatureNeurons#8]
Hello! I'm Ariel Berardino, a PhD student from Universidad de Buenos Aires. I just wanted to say congratulations on your excellent work on "Molecular landscapes of human hippocampal immature neurons across lifespan." I was wondering if you could possibly send me the cell's metadata (cell types) from the human hip prenatal, infant, child, adolescent, adult, and aging.

Thank you in advance and congratulations once again for your work.

**Comment by zhoujoeyyi** [comment]
Hi @ariberar  ,
Sure, happy to. Please email me at [zhouyi@ion.ac.cn](mailto:zhouyi@ion.ac.cn) so that I can share the cell annotation files with your email through a Google Drive link.

Best,
Joey

**Comment by zhoujoeyyi** [comment]
Hi Ariel @ariberar ,
Sure, happy to. Please drop me an email at [zhouyi@ion.ac.cn](mailto:zhouyi@ion.ac.cn) so that I can share the cell annotation files with your email through a Google Drive link.

Congratulations to you and Alejandro's lab on the beautiful preprint!


Best,

Joey

**Comment by zhoujoeyyi** [comment]
Hi Ariel @ariberar ,

Sure, happy to. Please drop me an email at [zhouyi@ion.ac.cn](mailto:zhouyi@ion.ac.cn) so that I can share the cell annotation files via a Google Drive link.

Congratulations to you and Alejandro's lab on the beautiful preprint!


Best,
Joey
